config/routes.rb
Rails.application.routes.draw do
  resources :approves

  resources :news_letters do
    collection do
      post :adding_email
      get :send_mail
      end
      member do 
        get :unsubscribe
      end
  end

  resources :teams

 devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks" }

  
  resources :blogs do
    collection do
      get :search
      get :search_sphinx
      get :latest_blogs
      get :display_category
      get :display_tags
    end
  end

resources :users do
  collection do
    post :permissions
  end
end

 root 'blogs#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>My Blogs</title>
  <link rel="shortcut icon" src="/assets/icons/favicon.ico">
  <link rel="apple-touch-icon" href="/assets/icons/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/assets/icons/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/assets/icons/apple-touch-icon-114x114.png">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet"/>    
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=true"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="color-light-blue">
<div id="fb-root"></div>
  <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
<%= disqus_init %>
<div id="page-wrapper" class="">
  <div class="top-header hidden-xs hidden-sm">
      <div class="container">
          <div class="pull-right">
                    <% if user_signed_in? %>
                    <%= link_to "LOGOUT", destroy_user_session_path,:method => :delete %>
                    <% end %>
            </div>
        </div>
    </div>
<%= yield %>
<div class="col-md-4 hidden-xs hidden-sm">
                  <h3><i class="fa fa-envelope"></i>Newsletter</h3>
                    <p class="contact-text">Get in touch with new blogs</p>                   
                       <fieldset>
                          <div class="form-group nospace">
                              <div class="input-group" style="width:100%;">
                            <%= form_tag adding_email_news_letters_path, :method => 'post',:remote => true do %>
                              <%#= text_field_tag  :email %>
                              <%= text_field_tag('email', nil, class: 'form-control1') %>
                              <%= submit_tag 'Submit', class: 'btn btn-primary' %>
                              <%end%>                              
                                </div>
                            </div>
                        </fieldset><br>
                        <% unless flash[:notice].nil? %>
                        <span style="color:green"><%= flash[:notice] %></span>
                        <% end %>
                        <% unless flash[:warn].nil? %>
                        <span style="color:red"><%= flash[:warn] %></span>
                        <% end %>
                        </div>
                </div>
    </div>
</body>
</html>

app/views/layouts/sign_in.html.erb
<!DOCTYPE html>
<html>
<head>
    <!-- ==========================
      Meta Tags 
    =========================== -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- ==========================
      Title 
    =========================== -->
   <title>Rank Blog</title>
    
    <!-- ==========================
      Favicons 
    =========================== -->
  <link rel="shortcut icon" src="/assets/icons/favicon.ico">
  <link rel="apple-touch-icon" href="/assets/icons/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/assets/icons/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/assets/icons/apple-touch-icon-114x114.png">
    
    <!-- ==========================
      Fonts 
    =========================== -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet"/>
    
    <!-- ==========================
      CSS 
    =========================== -->
    
    <!-- ==========================
      JS 
    =========================== -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=true"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="color-light-blue">        
    <!-- ==========================
      FORMS - START 
    =========================== -->
  <section class="content-full bg-color-2">
      
        <header class="navbar navbar-default navbar-static-top">
            <div class="pull-left">
                <a href="<%= blogs_path %>" class="btn btn-primary btn-lg"><i class="fa fa-chevron-left"></i>Back to Homepage</a>
            </div>
            <div class="pull-right">
                <ul class="brands brands-inline brands-md brands-circle main">
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                </ul>
            </div>
        </header>
    <div class="container">
        <div class="forms-only">
            <h1>Rank</h1>
              <form>
                <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                    <fieldset>
                      <h2>Sign in</h2>
                        
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label for="email">Your email:<span>*</span></label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                                    <%= f.email_field :email, autofocus: true, :class => "form-control", :placeholder => "Email" %>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="form-group col-sm-12">
                                <label for="password">Your password:<span>*</span></label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-key"></i></span>
                                  <%= f.password_field :password, autocomplete: "off", :class => "form-control", :placeholder => "Password" %>
                                </div>
                            </div>
                        </div>
                                              
                        <div class="pull-left">
                            <button type="submit" id="send" class="btn btn-primary"><i class="fa fa-check"></i>Confirm</button>
                        </div>                        
                    </fieldset>
                    <%= render "devise/shared/links" %>
                  <% end %> 
                </form>               
            </div>
            </div>
    </section>  
</body>
</html>